name: Setup
description: Common setup steps for workflows

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: '.go-version'
        cache: true

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Install tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
      shell: bash

    - name: Download dependencies
      run: go mod download
      shell: bash
